Repository humanmade/altis-cms, pull requests merged in 2019-12, with the labels that each got.

#136 Remove maybe update checks on admin_init
  inc/remove_updates/namespace.php
Labels: backport v3-branch

#138 Remove all update_* and upgrade_network caps
  inc/remove_updates/namespace.php
Labels: backport v3-branch

#141 #123 Remove auto updates for core
  inc/remove_updates/namespace.php
Labels: backport v3-branch

#143 Don't show shared blocks UI if user cant edit posts
  inc/block_editor/namespace.php
Labels: backport v1-branch, backport v2-branch, backport v3-branch, bug

#148 Fix typo in index.php doc comment
  index.php
Labels: backport v3-branch

#151 Ensure permission check doesnt happen in CLI / early run context
  inc/block_editor/namespace.php
Labels: backport v1-branch, backport v2-branch, backport v3-branch

#161 Bootstrap module early
  load.php
Labels: backport v3-branch
