Repository humanmade/altis-cms, pull requests merged in 2022-10, with the labels that each got.

#658 Change Query Monitor styling.
  assets/admin-color-scheme.css
Labels: backport v11-branch, backport v12-branch, backport v13-branch

#668 Update to WordPress 5.9.5
  composer.json
Labels: backport v11-branch

#667 Update to WordPress 6.0.3
  composer.json
Labels: backport v13-branch

#670 Update to WordPress 5.8.6
  composer.json
Labels: backport v9-branch
